### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'conf.yaml'

### ISSUE THREAD

**Issue by cohrah** [JarodMica/audiosplitter_whisper#1]
Everything ran perfect until the last step with
`python split_audio.py`

returned

`Traceback (most recent call last):
  File "E:\voice stuff\audiosplitter_whisper\split_audio.py", line 11, in <module>
    with open("conf.yaml", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'conf.yaml'`

**Comment by JarodMica** [comment]
> Everything ran perfect until the last step with `python split_audio.py`
> 
> returned
> 
> `Traceback (most recent call last): File "E:\voice stuff\audiosplitter_whisper\split_audio.py", line 11, in <module> with open("conf.yaml", "r") as file: FileNotFoundError: [Errno 2] No such file or directory: 'conf.yaml'`

Make sure you rename conf_example.yaml to conf.yaml :)!

**Comment by cohrah** [comment]
Seems to have fixed that issue. Now I'm running into another. I am using windows 11, python 3.10.7.  VS Code 17.9.2

When I start the debug I get:
`Failed to create virtual environment. Error: [Errno 13] Permission denied: 'C:\\Users\\codyr\\OneDrive\\Desktop\\modelmakerstuff\\audiosplitter_whisper\\venv\\Scripts\\python.exe'`

Seems to work fine with powershell but not with vs code. Most likely not a you thing but maybe you can help with it.

**Comment by JarodMica** [comment]
Original issue fixed, closing this issue.  For the other one, this tells me it's probably vscode permissions, so you might want to run it as admin and see if that resolves anything.
