### ISSUE TITLE
Exception has occurred: SystemExit

### ISSUE THREAD

**Issue by Necn0** [JarodMica/audiosplitter_whisper#20]
When i try to run and debug the setup-cuda.py script inside Visual Studio I get the following error:

"Exception has occurred: SystemExit
1
  File "E:\train\audiosplitter_whisper\setup-cuda.py", line 9, in create_virtual_environment
    venv.create('venv', with_pip=True)
PermissionError: [Errno 13] Permission denied: 'E:\\train\\audiosplitter_whisper\\venv\\Scripts\\python.exe'

During handling of the above exception, another exception occurred:

  File "E:\train\audiosplitter_whisper\setup-cuda.py", line 12, in create_virtual_environment
    sys.exit(1)
  File "E:\train\audiosplitter_whisper\setup-cuda.py", line 30, in main
    create_virtual_environment()
  File "E:\train\audiosplitter_whisper\setup-cuda.py", line 34, in <module>
    main()
SystemExit: 1"

Any idea how to fix this? Sorry if its an obvious problem I'm pretty new to all of this and I am following the video guide.

**Comment by JU57F0R1U1Z** [comment]
Check the version of Python in lower right corner in VS Code, maybe you're using the "venv" version of python, if its venv version set it back to the normal Pyton 3.10.11 64-bit. After that everything should work normaly.

**Comment by Necn0** [comment]
That was the problem, I switched it and it's working now. Thank you very much for your help.
