### ISSUE TITLE
Erorr (Requested float16 compute type, but the target device or backend do not support efficient float16 computation.)

### ISSUE THREAD

**Issue by Zafkieldark** [JarodMica/audiosplitter_whisper#4]
Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
Please help me

**Comment by JarodMica** [comment]
What GPU are you using? It should choose int8 as the compute type if it detects you are running a CPU

**Comment by Zafkieldark** [comment]
Hello i change float32 no 8 and work.my project work.

среда, 5 июля 2023 г. пользователь Jarod Mica ***@***.***>
написал:

**Comment by Zafkieldark** [comment]
My gpu nvidia gtx 1070.i change float16 on float 32,and my work project.

четверг, 6 июля 2023 г. пользователь Zafkiel ***@***.***>
написал:

**Comment by JarodMica** [comment]
Issue seems resolved
